config/routes.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Owums::Application.routes.draw do
  #### Named Routes --->
  match '/account/login' => 'account_sessions#new', :as => :account_login
  match '/account/logout' => 'account_sessions#destroy', :as => :account_logout, :via => 'delete'
  match '/account/signup' => 'accounts#new', :as => :account_registration
  match '/account/instructions' => 'accounts#instructions', :as => :account_instructions
  match '/account/reset' => 'password_resets#new', :as => :password_reset
  match '/account/verification' => 'accounts#verification', :as => :verification
  match '/account/status.json' => 'accounts#status_json', :as => :account_status
  match '/account/verify_paypal' => 'accounts#verify_paypal', :as => :verify_paypal, :via => 'post'
  match '/account/secure_verify_paypal' => 'accounts#secure_verify_paypal', :as => :secure_verify_paypal, :via => 'post'
  match '/account/gestpay_verify_credit_card' => 'accounts#gestpay_verify_credit_card', :as => :gestpay_verify_credit_card, :via => 'post'
  match '/account/gestpay_verified_by_visa' => 'accounts#gestpay_verified_by_visa', :as => :gestpay_verified_by_visa, :via => 'post'

  match '/users/browse' => 'users#index', :as => :users_browse
  match '/users/search' => 'users#search', :as => :users_search
  match '/users/find' => 'users#find', :via => 'post'

  match '/mobile_phone_password_resets/:id/recovery_confirmation' => 'mobile_phone_password_resets#recovery_confirmation', :as => :recovery_confirmation

  captcha_route
  match '/spoken_captcha.mp3' => 'spoken_captcha#show', :as => :spoken_captcha

  match '/operator/login' => 'operator_sessions#new', :as => :operator_login
  match '/operator/logout' => 'operator_sessions#destroy', :as => :operator_logout, :via => :delete

  match '/toggle_mobile' => 'application#toggle_mobile', :as => :toggle_mobile
  ####################

  #### Resources --->
  resource :account do
    resources :stats, :only => :show
  end
  resource :account_session
  resource :operator_session
  resources :configurations
  resources :users do
    resources :stats, :only => :show
    resources :radius_checks
    resources :radius_replies
    resources :radius_accountings, :only => :index # API method
  end
  resources :radius_groups do
    resources :radius_checks
    resources :radius_replies
  end
  resources :online_users, :only => :index # API method
  resources :radius_accountings, :only => :index # API method
  resources :operators
  resources :password_resets
  resources :email_password_resets

  resources :mobile_phone_password_resets do
    get :verification, :on => :member
  end

  resources :stats, :only => [:index, :show] do
    post :export, :on => :collection
  end
  ###################

  #### Root Route --->
  root :to => "account_sessions#new"
  #### root :to => "accounts#instructions" ->
end

app/models/configuration.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Configuration < ActiveRecord::Base

  validates_presence_of :key
  validates_format_of :key, :with => /\A[a-z_\.,]+\Z/

  attr_accessible :key, :value, :system_key
  
  after_save :invalidate_cache
  after_create :invalidate_cache
  after_destroy :invalidate_cache
  
  @@cache = nil
  
  def self.cache
    cache_key = "owums_settings"
    
    if @@cache.nil?
      # retrieve settings from cache if present
      @@cache = Rails.cache.fetch(cache_key)
    end
    
    # otherwise retrieve from database and create the hash we will cache
    if @@cache.nil?
      @@cache = {}
      
      Configuration.all.each do |config|
        @@cache[config.key.to_sym] = config.value
      end
      
      Rails.cache.write(cache_key, @@cache)
    end
    
    @@cache
  end
  
  def invalidate_cache
    @@cache = nil
    Rails.cache.delete("owums_settings")
  end

  def self.get(key, default=false)
    # load from DB if necessary
    if @@cache.nil?
      self.cache()
    end
    
    # return from cache
    unless @@cache[key.to_sym].nil?
      return @@cache[key.to_sym]
    # otherwise try retrieving from DB
    else
      # get key method, can provide default value
      res = Configuration.find_by_key(key)
      # neither result and neither a default value return nil
      if res.nil? and not default
        nil
      # no result but default value return default
      elsif res.nil?
        default
      # if found a result, update the cache and return the value
      else
        res.invalidate_cache
        res.value
      end
    end
  end

  def self.set(key, value)
    if prev = Configuration.find_by_key(key)
      prev.set(value)
    else
      Configuration.new(:key => key, :value => value).save!
    end
  end

  def set(value = '')
    self.system_key? && raise("BUG: key " + key + "is readonly!")
    self.value = value
    self.save!
  end
  
  def system_key?
    self.system_key
  end
end

app/controllers/configurations_controller.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class ConfigurationsController < ApplicationController
  before_filter :require_operator
  skip_before_filter :set_mobile_format

  access_control do
    default :deny

    allow :configurations_manager
  end

  def edit
    @configuration = Configuration.find(params[:id])
    
    html_configs = [
      'verification_explain_mobile_it',
      'verification_explain_mobile_en',
      'verification_explain_creditcard_it',
      'verification_explain_creditcard_en',
      'custom_account_instructions_it',
      'custom_account_instructions_en',
      'invoice_owner_en',
      'invoice_owner_it'
    ]
    
    @html = html_configs.include?(@configuration.key)
  end

  def update
    @configuration = Configuration.find(params[:id])
    if @configuration.update_attributes(params[:configuration])
      flash[:notice] = I18n.t(:Configuration_key_updated)
      redirect_to configurations_path
    else
      render :action => :edit
    end
  end

  def index
    @configurations = Configuration.order("configurations.key")
  end

end

app/views/configurations/edit.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<% content_for :after_defaults do %>
  <%= stylesheet_link_tag 'jHtmlArea/jHtmlArea' %>
  <%= javascript_include_tag "jHtmlArea-0.7.5.min" %>
<% end %>

<div class="grid_12">
  <div class="box">
    <h2><%=t :Edit_configuration_key %></h2>
    
    <%= form_for @configuration do |f| %>
      <fieldset>
        <legend><strong><%=t :Key %>:</strong> <%= @configuration.key %></legend>
          <p>
            <strong><%= label_tag t(:value) %>:</strong>
            <br />
            <%= f.text_area :value %>
          </p>
          <p>
            <%= f.submit t(:Update), :class => 'submit button' %>
          </p>
      </fieldset>
    <% end %>
  </div>
</div>
<% if @html %>
  <script type="text/javascript">
    $('textarea').htmlarea({
      css: '<%= root_url %>stylesheets/jHtmlArea/jHtmlArea.Editor.css'
    });
  </script>
<% end %>

app/views/configurations/index.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <div class="box">
    <h2><%=t :Configuration_keys %></h2>

    <table id="configuration_keys" class="hover">
      <thead>
        <tr>
          <th class="key"><%=t :Key %></th>
          <th class="value"><%=t :Value %></th>
          <th class="operations"><%=t :Operations %></th>
        </tr>
      </thead>
      <tbody>
        <% @configurations.each do |configuration| %>
          <tr class="hover">
            <td class="first key"><strong><%= configuration.key %></strong></td>
            <td class="value"><%= simple_format(configuration.value.html_safe) %></td>
            <td class="operations"><%= link_to t(:Edit), edit_configuration_path(configuration) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <script type="text/javascript">
      $('#configuration_keys td').click(function(e){
        location.href = $(this).parent().find('.operations a').attr('href');
      });
    </script>
  </div>
</div>