config/routes.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Owums::Application.routes.draw do
  #### Named Routes --->
  match '/account/login' => 'account_sessions#new', :as => :account_login
  match '/account/logout' => 'account_sessions#destroy', :as => :account_logout, :via => 'delete'
  match '/account/signup' => 'accounts#new', :as => :account_registration
  match '/account/instructions' => 'accounts#instructions', :as => :account_instructions
  match '/account/reset' => 'password_resets#new', :as => :password_reset
  match '/account/verification' => 'accounts#verification', :as => :verification
  match '/account/status.json' => 'accounts#status_json', :as => :account_status
  match '/account/verify_paypal' => 'accounts#verify_paypal', :as => :verify_paypal, :via => 'post'
  match '/account/secure_verify_paypal' => 'accounts#secure_verify_paypal', :as => :secure_verify_paypal, :via => 'post'
  match '/account/gestpay_verify_credit_card' => 'accounts#gestpay_verify_credit_card', :as => :gestpay_verify_credit_card, :via => 'post'
  match '/account/gestpay_verified_by_visa' => 'accounts#gestpay_verified_by_visa', :as => :gestpay_verified_by_visa, :via => 'post'

  match '/users/browse' => 'users#index', :as => :users_browse
  match '/users/search' => 'users#search', :as => :users_search
  match '/users/find' => 'users#find', :via => 'post'

  match '/mobile_phone_password_resets/:id/recovery_confirmation' => 'mobile_phone_password_resets#recovery_confirmation', :as => :recovery_confirmation

  captcha_route
  match '/spoken_captcha.mp3' => 'spoken_captcha#show', :as => :spoken_captcha

  match '/operator/login' => 'operator_sessions#new', :as => :operator_login
  match '/operator/logout' => 'operator_sessions#destroy', :as => :operator_logout, :via => :delete

  match '/toggle_mobile' => 'application#toggle_mobile', :as => :toggle_mobile
  ####################

  #### Resources --->
  resource :account do
    resources :stats, :only => :show
  end
  resource :account_session
  resource :operator_session
  resources :configurations
  resources :users do
    resources :stats, :only => :show
    resources :radius_checks
    resources :radius_replies
    resources :radius_accountings, :only => :index # API method
  end
  resources :radius_groups do
    resources :radius_checks
    resources :radius_replies
  end
  resources :online_users, :only => :index # API method
  resources :radius_accountings, :only => :index # API method
  resources :operators
  resources :password_resets
  resources :email_password_resets

  resources :mobile_phone_password_resets do
    get :verification, :on => :member
  end

  resources :stats, :only => [:index, :show] do
    post :export, :on => :collection
  end
  ###################

  #### Root Route --->
  root :to => "account_sessions#new"
  #### root :to => "accounts#instructions" ->
end

app/controllers/email_password_resets_controller.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class EmailPasswordResetsController < ApplicationController
  before_filter :load_account_using_perishable_token, :only => [:edit, :update]
  before_filter :require_no_account

  def new

    respond_to do |format|
      format.html
      format.mobile
      format.xml { render_if_xml_restful_enabled }
    end
  end

  def create
    @account = Account.find_by_email(params[:email_password_reset][:email]) if params[:email_password_reset]
    if @account
      @account.password_reset_instructions!
      flash[:notice] = I18n.t(:Instruction_reset_has_been_mailed)

      respond_to do |format|
        format.html { redirect_to root_url }
        format.mobile { redirect_to root_url }
        format.xml { render_if_xml_restful_enabled :nothing => true, :status => :created }
      end
    else
      flash[:notice] = I18n.t(:No_user_found_with_that_email)

      respond_to do |format|
        format.html { render :action => :new }
        format.mobile { render :action => :new }
        format.xml { render_if_xml_restful_enabled :nothing => true, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.mobile
      format.xml { render_if_xml_restful_enabled }
    end
  end

  def update
    @account.password = params[:account][:password]
    @account.password_confirmation = params[:account][:password_confirmation]
    password_changed = @account.changed?

    if @account.save_without_session_maintenance
      flash[:notice] = I18n.t(password_changed ? :Password_successfully_updated : :Password_not_successfully_updated)

      respond_to do |format|
        format.html { redirect_to root_url }
        format.mobile { redirect_to root_url }
        format.xml { render_if_xml_restful_enabled :nothing => true, :status => :accepted }
      end
    else
      respond_to do |format|
        format.html   { render :action => :edit }
        format.mobile { render :action => :edit }
        format.xml { render_if_xml_restful_enabled :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
  def load_account_using_perishable_token
    @account = Account.find_using_perishable_token(params[:id])
    unless @account
      flash[:notice] = I18n.t(:Perishable_token_error)

      respond_to do |format|
        format.html { redirect_to root_url }
        format.mobile { redirect_to root_url }
        format.xml { render_if_xml_restful_enabled :nothing => true, :status => :forbidden }
      end
    end
  end
end

app/views/email_password_resets/edit.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_8 prefix_2 suffix_2">
  <div class="box">
    <%= simple_form_for @account, :url => email_password_reset_path do |f| %>
        <%= render 'common/form_elements/password_reset', :form => f, :owner => @account %>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/email_password_resets/edit.mobile.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<% content_for :header do %>
    <h1><%=t :Edit %></h1>
<% end %>

<% content_for :back do %>
    <%= mobile_link_back_to root_path, 'data-ajax' => false %>
<% end %>

<%= simple_form_for @account, :url => email_password_reset_path, :html => {'data-ajax' => false} do |f| %>
    <%= render 'common/form_elements/password_reset', :form => f, :owner => @account %>
<% end %>

app/views/email_password_resets/new.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_6 prefix_3 suffix_3">
  <div class="box">
    <div class="block" id="forgot_password">
      <%= form_tag email_password_resets_path do %>
        <fieldset>
          <legend><%=t :Forgot_password %></legend>
          <p>
            <%=t :Forgot_password_description_email %>
            <br />
            <b><label><%=t :Email %></label></b>
            <br />
            <%= text_field_tag "email_password_reset_email", '', :name => 'email_password_reset[email]' %>
          </p>
          <p>
            <%= submit_tag t(:Reset_password), :class => 'submit button nomargin' %>
          </p>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/email_password_resets/new.mobile.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<%= content_for :data_url, email_password_resets_path %>

<% content_for :header do %>
    <h1><%=t :Recover %></h1>
<% end %>

<% content_for :back do %>
    <%= mobile_link_back_to new_password_reset_path %>
<% end %>

<%= form_tag email_password_resets_path, 'data-ajax' => false do %>
    <ul data-role="listview" data-inset="true">
      <li data-role="fieldcontain">
        <%=t :Forgot_password_description_email_for_mobile %>
      </li>

      <li data-role="fieldcontain">
        <label><%=t :Email %></label>
        <%= text_field_tag "email_password_reset_email", {}, :name => 'email_password_reset[email]' %>
      </li>

      <li data-role="fieldcontain">
        <%= submit_tag t(:Reset) %>
      </li>
    </ul>
<% end %>