config/routes.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Owums::Application.routes.draw do
  #### Named Routes --->
  match '/account/login' => 'account_sessions#new', :as => :account_login
  match '/account/logout' => 'account_sessions#destroy', :as => :account_logout, :via => 'delete'
  match '/account/signup' => 'accounts#new', :as => :account_registration
  match '/account/instructions' => 'accounts#instructions', :as => :account_instructions
  match '/account/reset' => 'password_resets#new', :as => :password_reset
  match '/account/verification' => 'accounts#verification', :as => :verification
  match '/account/status.json' => 'accounts#status_json', :as => :account_status
  match '/account/verify_paypal' => 'accounts#verify_paypal', :as => :verify_paypal, :via => 'post'
  match '/account/secure_verify_paypal' => 'accounts#secure_verify_paypal', :as => :secure_verify_paypal, :via => 'post'
  match '/account/gestpay_verify_credit_card' => 'accounts#gestpay_verify_credit_card', :as => :gestpay_verify_credit_card, :via => 'post'
  match '/account/gestpay_verified_by_visa' => 'accounts#gestpay_verified_by_visa', :as => :gestpay_verified_by_visa, :via => 'post'

  match '/users/browse' => 'users#index', :as => :users_browse
  match '/users/search' => 'users#search', :as => :users_search
  match '/users/find' => 'users#find', :via => 'post'

  match '/mobile_phone_password_resets/:id/recovery_confirmation' => 'mobile_phone_password_resets#recovery_confirmation', :as => :recovery_confirmation

  captcha_route
  match '/spoken_captcha.mp3' => 'spoken_captcha#show', :as => :spoken_captcha

  match '/operator/login' => 'operator_sessions#new', :as => :operator_login
  match '/operator/logout' => 'operator_sessions#destroy', :as => :operator_logout, :via => :delete

  match '/toggle_mobile' => 'application#toggle_mobile', :as => :toggle_mobile
  ####################

  #### Resources --->
  resource :account do
    resources :stats, :only => :show
  end
  resource :account_session
  resource :operator_session
  resources :configurations
  resources :users do
    resources :stats, :only => :show
    resources :radius_checks
    resources :radius_replies
    resources :radius_accountings, :only => :index # API method
  end
  resources :radius_groups do
    resources :radius_checks
    resources :radius_replies
  end
  resources :online_users, :only => :index # API method
  resources :radius_accountings, :only => :index # API method
  resources :operators
  resources :password_resets
  resources :email_password_resets

  resources :mobile_phone_password_resets do
    get :verification, :on => :member
  end

  resources :stats, :only => [:index, :show] do
    post :export, :on => :collection
  end
  ###################

  #### Root Route --->
  root :to => "account_sessions#new"
  #### root :to => "accounts#instructions" ->
end

app/models/account_session.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class AccountSession < Authlogic::Session::Base
  generalize_credentials_error_messages I18n.t(:Login_error)
end

app/controllers/account_sessions_controller.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class AccountSessionsController < ApplicationController
  before_filter :require_no_account, :only => [:new, :create]
  before_filter :require_account, :only => :destroy

  def new
    @account_session = AccountSession.new

    respond_to do |format|
      format.html
      format.mobile
      format.xml { render_if_xml_restful_enabled }
    end
  end

  def create
    @account_session = AccountSession.new(params[:account_session])
    if @account_session.save
      flash[:notice] = I18n.t(:Login_successful)
      #Avoids session fixations
      keep_session_data :locale do
        reset_session
      end

      respond_to do |format|
        format.html { redirect_to account_url }
        format.mobile { redirect_to account_url }
        format.xml { render_if_xml_restful_enabled :nothing => true, :status => :created }
      end
    else
      respond_to do |format|
        format.html   { render :action => :new }
        format.mobile { render :action => :new }
        format.xml    { render_if_xml_restful_enabled :xml => @account_session.errors, :status => :unauthorized }
      end
    end
  end

  def destroy
    current_account_session.destroy
    flash[:notice] = I18n.t(:Logout_successful)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.mobile { redirect_to root_path }
      format.xml { render_if_xml_restful_enabled :nothing => true }
    end

  end
end

app/views/account_sessions/_new.mobile.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<% content_for :header do %>
    <h1><%=t :Login %></h1>
<% end %>

<% content_for :back do %>
    <%= mobile_link_back_to root_path %>
<% end %>


<%= simple_form_for @account_session, :url => account_session_path do |f| %>
    <% if @account_session.errors.any? %>
        <div data-role="collapsible">
          <h3><%=t :header, :count => @account_session.errors.count, :scope => [ :errors, :template ] %></h3>
          <p><%= f.error_messages %></p>
        </div>
    <% end %>

    <ul data-role="listview" data-inset="true">
      <li data-role="fieldcontain">
        <% if Configuration.get('use_mobile_phone_as_username') == "true"  %>
            <%= f.input :username, :label => t(:Username_or_mobile_or_email) %>
        <% else %>
            <%= f.input :username %>
        <% end %>
      </li>

      <li data-role="fieldcontain">
        <%= f.input :password %>
      </li>

      <li data-role="fieldcontain">
        <%= f.input_field :remember_me, :as => :boolean %>
        <%= f.label :remember_me %>
      </li>

      <li>
        <%= f.button :submit %>
      </li>
    </ul>
<% end %>

app/views/account_sessions/new.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_6 prefix_3 suffix_3">
  <div class="box">
    <div class="block" id="login">
      <%= simple_form_for @account_session, :url => account_session_path do |f| %>
          <fieldset>
            <legend><%=t :Login %></legend>
            <p><%= f.error_messages %></p>

            <% if Configuration.get('use_mobile_phone_as_username') == "true" %>
                <%= f.input :username, :label => t(:Username_or_mobile_or_email) %>
            <% else %>
                <%= f.input :username %>
            <% end %>

            <%= f.input :password %>

            <div id="remember_me" style="float:left; width:50%">
              <%= f.input :remember_me, :as => :boolean %>

            </div>
            <div style="float:right">
              <a style="font-size:12px" href="/account/reset">Password reset</a>
            </div>

            <%= f.button :submit, :class => 'submit button nomargin' %>
            <br>
          </fieldset>
      <% end %>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/account_sessions/new.mobile.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<% content_for :header do %>
    <h1><%=t :Login %></h1>
<% end %>

<% content_for :back do %>
    <%= mobile_link_back_to root_path %>
<% end %>


<%= simple_form_for @account_session, :url => account_session_path do |f| %>
    <% if @account_session.errors.any? %>
        <div data-role="collapsible">
          <h3><%=t :header, :count => @account_session.errors.count, :scope => [ :errors, :template ] %></h3>
          <p><%= f.error_messages %></p>
        </div>
    <% end %>

    <ul data-role="listview" data-inset="true">
      <li data-role="fieldcontain">
        <% if Configuration.get('use_mobile_phone_as_username') == "true"  %>
            <%= f.input :username, :label => t(:Username_or_mobile_or_email) %>
        <% else %>
            <%= f.input :username %>
        <% end %>
      </li>

      <li data-role="fieldcontain">
        <%= f.input :password %>
      </li>

      <li data-role="fieldcontain">
        <%= f.input_field :remember_me, :as => :boolean %>
        <%= f.label :remember_me %>
      </li>

      <li>
        <%= f.button :submit %>
      </li>
    </ul>
<% end %>