config/routes.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Owums::Application.routes.draw do
  #### Named Routes --->
  match '/account/login' => 'account_sessions#new', :as => :account_login
  match '/account/logout' => 'account_sessions#destroy', :as => :account_logout, :via => 'delete'
  match '/account/signup' => 'accounts#new', :as => :account_registration
  match '/account/instructions' => 'accounts#instructions', :as => :account_instructions
  match '/account/reset' => 'password_resets#new', :as => :password_reset
  match '/account/verification' => 'accounts#verification', :as => :verification
  match '/account/status.json' => 'accounts#status_json', :as => :account_status
  match '/account/verify_paypal' => 'accounts#verify_paypal', :as => :verify_paypal, :via => 'post'
  match '/account/secure_verify_paypal' => 'accounts#secure_verify_paypal', :as => :secure_verify_paypal, :via => 'post'
  match '/account/gestpay_verify_credit_card' => 'accounts#gestpay_verify_credit_card', :as => :gestpay_verify_credit_card, :via => 'post'
  match '/account/gestpay_verified_by_visa' => 'accounts#gestpay_verified_by_visa', :as => :gestpay_verified_by_visa, :via => 'post'

  match '/users/browse' => 'users#index', :as => :users_browse
  match '/users/search' => 'users#search', :as => :users_search
  match '/users/find' => 'users#find', :via => 'post'

  match '/mobile_phone_password_resets/:id/recovery_confirmation' => 'mobile_phone_password_resets#recovery_confirmation', :as => :recovery_confirmation

  captcha_route
  match '/spoken_captcha.mp3' => 'spoken_captcha#show', :as => :spoken_captcha

  match '/operator/login' => 'operator_sessions#new', :as => :operator_login
  match '/operator/logout' => 'operator_sessions#destroy', :as => :operator_logout, :via => :delete

  match '/toggle_mobile' => 'application#toggle_mobile', :as => :toggle_mobile
  ####################

  #### Resources --->
  resource :account do
    resources :stats, :only => :show
  end
  resource :account_session
  resource :operator_session
  resources :configurations
  resources :users do
    resources :stats, :only => :show
    resources :radius_checks
    resources :radius_replies
    resources :radius_accountings, :only => :index # API method
  end
  resources :radius_groups do
    resources :radius_checks
    resources :radius_replies
  end
  resources :online_users, :only => :index # API method
  resources :radius_accountings, :only => :index # API method
  resources :operators
  resources :password_resets
  resources :email_password_resets

  resources :mobile_phone_password_resets do
    get :verification, :on => :member
  end

  resources :stats, :only => [:index, :show] do
    post :export, :on => :collection
  end
  ###################

  #### Root Route --->
  root :to => "account_sessions#new"
  #### root :to => "accounts#instructions" ->
end

app/models/radius_group.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class RadiusGroup < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_numericality_of :priority

  has_and_belongs_to_many :account_commons, :join_table => 'radius_groups_users', :association_foreign_key => :user_id
  has_many :radius_checks, :as => :radius_entity, :dependent => :destroy
  has_many :radius_replies, :as => :radius_entity, :dependent => :destroy

  attr_accessible :name, :priority, :notes

  def radius_name
    name
  end

end

app/controllers/radius_groups_controller.rb
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class RadiusGroupsController < ApplicationController
  before_filter :require_operator
  before_filter :load_radius_group, :except => [ :index, :new, :create ]

  skip_before_filter :set_mobile_format

  access_control do
    default :deny

    allow :radius_groups_creator,   :to => [ :new, :create ]
    allow :radius_groups_viewer,    :to => [ :index, :show ]
    allow :radius_groups_manager,   :to => [ :edit, :update ]
    allow :radius_groups_destroyer, :to => [ :destroy ]
  end

  respond_to :html, :xml, :json

  # GET /radius_groups
  def index
    respond_with(@radius_groups = RadiusGroup.all(:order => [:priority, :name]))
  end

  # GET /radius_groups/:id
  def show
    respond_with(@radius_group)
  end

  # GET /radius_groups/new
  def new
    respond_with(@radius_group = RadiusGroup.new)
  end

  # POST /radius_groups
  def create
    @radius_group = RadiusGroup.create(params[:radius_group])

    respond_with(@radius_group, :location => radius_groups_url)
  end

  # GET /radius_groups/:id/edit
  def edit
    respond_with(@radius_group)
  end

  # PUT /radius_groups/:id
  def update
    @radius_group.update_attributes(params[:radius_group])

    respond_with(@radius_group, :location => radius_groups_url)
  end

  # DELETE /radius_groups/:id
  def destroy
    @radius_group.destroy

    respond_to do |format|
      format.html { redirect_to radius_groups_url }
      format.any { render :nothing => true, :status => :ok }
    end
  end

  private

  def load_radius_group
    @radius_group = RadiusGroup.find(params[:id])
  end

end

app/views/radius_groups/_form.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<%= form_for @radius_group do |f| %>
    <fieldset>
      <legend><strong><%=t :Radius_group %>:</strong> <%= @radius_group.name %></legend>
      <p><%= f.error_messages %></p>

      <p>
        <strong><%= label_tag t(:Name) %>:</strong>
        <br />
        <%= f.text_field :name %>
      </p>

      <p>
        <strong><%= label_tag t(:Priority) %>:</strong>
        <br />
        <%= f.text_field :priority %>
      </p>

      <p>
        <strong><%= label_tag t(:Notes) %>:</strong>
        <br />
        <%= f.text_area :notes, :rows => 4 %>
      </p>

      <p>
        <% if @radius_group.new_record? %>
            <%= f.submit t(:Create), :class => 'submit button nomargin' %>
        <% else %>
            <%= f.submit t(:Edit), :class => 'submit button nomargin' %>
        <% end %>
      </p>
    </fieldset>
<% end %>

app/views/radius_groups/_list.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div id="search_results">
  <table>
    <thead>
    <tr>
      <th scope="col"><%= t :Priority %></th>
      <th scope="col"><%= t :Name %></th>
      <%
         if current_operator.has_role?('radius_groups_manager') ||
                 current_operator.has_role?('radius_groups_destroyer')
      %>
          <th scope="col"><%= t :Notes %></th>
          <th scope="col"><%= t :Operations %></th>
      <% end %>
    </tr>
    </thead>

    <tbody>
    <% radius_groups.each do |radius_group| %>
        <tr>
          <td><%= radius_group.priority %></td>
          <td><%= link_to h(radius_group.name), radius_group_url(radius_group) %></td>
          <td><%= truncate(radius_group.notes, :length => 20) %></td>
          <td>
            <% if current_operator.has_role? 'radius_groups_manager' %>
                <%= link_to t(:Edit), edit_radius_group_url(radius_group) %>
            <% end %>
            &nbsp;
            <% if current_operator.has_role? 'radius_groups_destroyer' %>
                <%= link_to t(:Destroy), radius_group_url(radius_group),
                            :confirm => t(:Are_you_sure), :method => :delete %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="4"><%= link_to t(:New_radius_group), new_radius_group_url, :class => 'button' %></td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/radius_groups/edit.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <div class="box">
    <h2><%=t :Edit_radius_group %></h2>

    <%= render 'form' %>

  </div>
</div>

app/views/radius_groups/index.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <div class="box">
    <h2><%=t :Radius_groups %></h2>
      <div class="block" id="search_block">
        <%= render 'list', :radius_groups => @radius_groups %>
      </div>
  </div>
</div>

<div class="clear"></div>

app/views/radius_groups/new.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <div class="box">
    <h2><%=t :New_radius_group %></h2>

    <%= render 'form' %>

  </div>
</div>

app/views/radius_groups/show.html.erb
<%#
# This file is part of the OpenWISP User Management System
#
# Copyright (C) 2012 OpenWISP.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#%>

<div class="grid_12">
  <h2><%= t :Radius_group %> <%= @radius_group.name %></h2>
  <div id="radius_group_info" class="box">
    <h2><%= t :Radius_group_info %></h2>
    <table>
      <tbody>
      <tr>
        <td><strong><%= t :Name %></strong></td>
        <td><%= @radius_group.name %></td>
      </tr>
      <tr>
        <td><strong><%= t :Priority %></strong></td>
        <td><%= @radius_group.priority %></td>
      </tr>
      <tr>
        <td><strong><%= t :Notes %></strong></td>
        <td><%= @radius_group.notes %></td>
      </tr>
      </tbody>
      <tfoot>
      <% if auth? :radius_groups_manager %>
          <tr>
            <td colspan="2">
              <p><%= link_to t(:Edit), edit_radius_group_url(@radius_group), :class => 'button nomargin' %></p>
            </td>
          </tr>
      <% end %>
      </tfoot>
    </table>
  </div>
</div>

<div class="grid_12">
  <% if auth? :radius_checks_viewer %>
      <div id="radius_group_checks" class="box">
        <h2><%= t :Radius_checks %></h2>
        <%= render :partial => 'radius_checks/list', :locals => { :subject => @radius_group } %>
      </div>
  <% end %>
  <% if auth? :radius_replies_viewer %>
      <div id="radius_group_replies" class="box">
        <h2><%= t :Radius_replies %></h2>
        <%= render :partial => 'radius_replies/list', :locals => { :subject => @radius_group } %>
      </div>
  <% end %>
</div>
<div class="clear"></div>